# Generated by Django 4.1.7 on 2023-03-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_pic_news_picname_news_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picname',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='picurl',
            field=models.FileField(default='-', upload_to=''),
        ),
    ]
