# Generated by Django 4.1.7 on 2023-04-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
