# Generated by Django 4.1.7 on 2023-03-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.CharField(default='-', max_length=250),
        ),
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
