# Generated by Django 4.1.7 on 2023-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_fb_article_ph_article_tw_article_yt'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ints',
            field=models.CharField(default='-', max_length=250),
        ),
    ]
