# Generated by Django 4.1.7 on 2023-03-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_ints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ints',
        ),
        migrations.AddField(
            model_name='article',
            name='picname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='picurl',
            field=models.TextField(default=''),
        ),
    ]
