# Generated by Django 4.1.7 on 2023-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_article_ints_article_picname_article_picurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picname2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='picurl2',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='picname',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='picurl',
            field=models.FileField(upload_to=''),
        ),
    ]
