# Generated by Django 4.1.7 on 2023-03-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_article_picname2_article_picurl2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bodylong',
            field=models.TextField(default='-'),
        ),
    ]
